FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update && \
    apt-get install -y \
    sudo \
    unzip \
    wget \
    build-essential \
    gfortran \
    cmake \
    perl \
    python3 \
    python-is-python3 \
    git-lfs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# openradiossのbinaryを解凍する
#COPY ./app/OpenRadioss_linux64.zip /opt/OpenRadioss_linux64.zip
RUN wget -P /opt/ https://github.com/OpenRadioss/OpenRadioss/releases/download/latest-20230624/OpenRadioss_linux64.zip && \
    unzip /opt/OpenRadioss_linux64.zip -d /opt/ 

WORKDIR /home/work